travis:
  secure:
    BINSTAR_TOKEN: cqvuu3o5rmfAVMsjY7qkkClNho67OcjfcrJFYUYn4Mg5Kr3vlkz7YX+aEFU4b143TLGvF4nxTbqIvehd/A/pbgXG+4K6TmhwyM2CAprQ1GBMr/eYxEjLrnz/geZU0WnhlcMfxYxHlm4iyHvS4cL1hv2rPhNcb4+W9EPh/WJTVbTxG8Q8MN+ro0juzDOlqqetdnl9t2HqWDDZ4SIMOXuWhBdqpGWGWe6zPNo+DQJ/sH9rv1RlnJP2/0YduXHlrQzz7N4jTOSaAELlsFuaxSsFfPxOsaSnW7GBNmynN7V5Ond+lAih8DbW2H6+agBMLq/0Cv9rrBNSHT6dkNpyrrwT9vcavCDl1Nrhgh1fKFN+mtcK0OBhhyrOn9SDdFpDRlYT0IpOs+GmSnzMb0xj1RW4xZLnk1oe+lUlyiGcsrb+8sLAp97INFM8CgFBc3Fw9UfneR8DMntaGYHROfQ5t8C4piAmUck/h33vanZtcZ1aZJScVo1o8VnfAJZ3LJWMe77PxDsqNuq5j8S+h6ysv9yC6YgZJevzuxkirzC8PAOh63qgot+EI8oYvKpwFfjt9RPTdK/3QaJYNDZNeSC3oCRTcdJpoI2tTzUGNb0mVfYaDpkwW66Nd0IKxB0Ztr3aJ23vytogDudCRkB223EHzdsz7Jkdgm6fAAZHI5i3YC5RoQQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
